### ISSUE TITLE
Plan to upgrade libreoffice to 24? 

### ISSUE THREAD

**Issue by yonghaoy** [linuxserver/docker-libreoffice#14]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Upgrade libreoffice to 24

### Reason for change

Libreoffice 7.6 end of life on June 12
https://wiki.documentfoundation.org/ReleasePlan, do we have plan to upgrade libreoffice? 

### Proposed code change

https://github.com/linuxserver/docker-libreoffice/blob/f222fbaddcb55830b0fce3a5e5604a626c62fdf9/Dockerfile#L6

**Comment by thespad** [comment]
That's a matter for the Alpine packagers really, right now they're [still packaging 7.6](https://pkgs.alpinelinux.org/packages?name=libreoffice&branch=v3.20&repo=&arch=&maintainer=).

Frankly it doesn't seem a *great* idea on the Libreoffice side to EOL both currently supported versions of their product within 6 months of each other and without another LTS version for people to move to yet.

**Comment by yonghaoy** [comment]
Thanks! @thespad . I will close this ticket and watch for https://pkgs.alpinelinux.org/packages?name=libreoffice&branch=v3.20&repo=&arch=&maintainer=

One more question before closing this, do you know how to prevent user from switching to root? Right now, user can switch to root in terminal by running `sudo -s`, and our security does not like this. 
Thanks

**Comment by thespad** [comment]
You've got a few options; you could uninstall sudo, you could remove the abc user from the wheel group, or you could edit the sudoers file, all via https://www.linuxserver.io/custom

**Comment by yonghaoy** [comment]
Thanks!

**Comment by shantanuo** [comment]
I can see libreoffice version 7.6 if I choose Alpine Branch 3.20.
But if I select "edge" branch, I can see version 25.2
Please upgrade libreoffice version to 25.2 because a lot of features have been added since version 7.6
