### ISSUE TITLE
Java Runtime Enviroment

### ISSUE THREAD

**Issue by wibbene** [linuxserver/docker-libreoffice#4]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

When using the Libreoffice Base, it says that there is not JRE (Java Runtime Enviroment) installed
------------------------------

## Expected Behavior

Java Runtime Enviroment should be installed
## Current Behavior

Java Runtime Enviroment is not installed
## Steps to Reproduce

1. Run this out of the box via Docker Compose

## Environment
**OS: Ubuntu 21.04 Server
**CPU architecture:** x86_64
**How docker service was installed:**
Via offical Documentation to install 
## Command used to create docker container (run/create/compose/screenshot)
 docker-compse up -d

## Manual Fix
Go into Docker Container and run `apk add openjdk8-jre`

**Comment by thelamer** [comment]
jre has been added in the latest version
