### ISSUE TITLE
LibreOffice 7.5 is out

### ISSUE THREAD

**Issue by mariushosting** [linuxserver/docker-libreoffice#8]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Linuxserver LibreOffice image point to the old version of LibreOffice 7.3 instead of 7.5 https://www.libreoffice.org/download/release-notes/

### Reason for change

New version new features.

**Comment by Roxedus** [comment]
We use the package in the [alpine repos](https://pkgs.alpinelinux.org/packages?name=libreoffice&branch=v3.17&repo=&arch=x86_64), we do not control this version

**Comment by mariushosting** [comment]
> We use the package in the [alpine repos](https://pkgs.alpinelinux.org/packages?name=libreoffice&branch=v3.17&repo=&arch=x86_64), we do not control this version

I understand, but you should use the alpine repos latest edge: https://pkgs.alpinelinux.org/packages?name=libreoffice&branch=edge&repo=community&arch=x86_64&maintainer=Timo+Ter%C3%A4s

**Comment by Roxedus** [comment]
We do not have a kasm image based on edge. installing a single package from edge will break stuff eventually.

**Comment by thespad** [comment]
This will happen when a stable Alpine release has the package version, probably in 3.18, which is the next planned stable release.
